export const REQUEST_MOVIES = 'MovieListContainer/REQUEST_MOVIES';
export const REQUEST_MOVIES_SUCCESS = 'MovieListContainer/REQUEST_MOVIES_SUCCESS';
export const REQUEST_MOVIES_FAIL = 'MovieListContainer/REQUEST_MOVIES_FAIL';

export const REQUEST_CINEMAS = 'MovieListContainer/REQUEST_CINEMAS';
export const REQUEST_CINEMAS_SUCCESS = 'MovieListContainer/REQUEST_CINEMAS_SUCCESS';
export const REQUEST_CINEMAS_FAIL = 'MovieListContainer/REQUEST_CINEMAS_FAIL';

export const SELECT_MOVIE = "MovieListContainer/SELECT_MOVIE";
export const SELECT_MOVIE_SUCCESS = "MovieListContainer/SELECT_MOVIE_SUCCESS";

export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST"; // send request to api
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";

export const DELETE_SESSION = "DELETE_SESSION";
export const CREATE_SESSION = "CREATE_SESSION";

export const REQUEST_UPDATE_MOVIE = "REQUEST_UPDATE_MOVIE";
export const UPDATE_MOVIE_SUCCESS = "UPDATE_MOVIE_SUCCESS";
export const UPDATE_MOVIE_FAIL = "UPDATE_MOVIE_FAIL";

export const REQUEST_ADD_MOVIE = "REQUEST_ADD_MOVIE";
export const ADD_MOVIE_SUCCESS = "ADD_MOVIE_SUCCESS";
export const ADD_MOVIE_FAIL = "ADD_MOVIE_FAIL";

export const REQUEST_DELETE_MOVIE = "REQUEST_DELETE_MOVIE";
export const DELETE_MOVIE_SUCCESS = "DELETE_MOVIE_SUCCESS";
export const DELETE_MOVIE_FAIL = "DELETE_MOVIE_FAIL";

export const RESET_API_RESULT = "RESET_API_RESULT";